### ISSUE TITLE
cannot import name 'appdirs' from 'pkg_resources.extern'

### ISSUE THREAD

**Issue by AnimusXCASH** [ApeX-Protocol/apexpro-openapi#20]
```
(d:\AlgorithmicTrading\algoStrategyBacktesting\.conda) D:\AlgorithmicTrading\algoStrategyBacktesting>d:/AlgorithmicTrading/algoStrategyBacktesting/.conda/python.exe d:/AlgorithmicTrading/algoStrategyBacktesting/apex_omni_main.py
Traceback (most recent call last):
  File "d:\AlgorithmicTrading\algoStrategyBacktesting\apex_omni_main.py", line 2, in <module>
    from apexpro.http_public import HttpPublic
  File "d:\AlgorithmicTrading\algoStrategyBacktesting\.conda\Lib\site-packages\apexpro\__init__.py", line 24, in <module>
    from web3 import Web3
  File "d:\AlgorithmicTrading\algoStrategyBacktesting\.conda\Lib\site-packages\web3\__init__.py", line 4, in <module>
    import pkg_resources
  File "d:\AlgorithmicTrading\algoStrategyBacktesting\.conda\Lib\site-packages\pkg_resources\__init__.py", line 73, in <module>
    from pkg_resources.extern import appdirs
ImportError: cannot import name 'appdirs' from 'pkg_resources.extern' (d:\AlgorithmicTrading\algoStrategyBacktesting\.conda\Lib\site-packages\pkg_resources\extern\__init__.py)  
```

**Comment by LiquidoCobra** [comment]
Same problem here
